---
title: "chad_huntebrinker_hw2_plots"
author: "Chad Huntebrinker"
date: "2024-09-09"
output:
  word_document: default
  html_document: default
---

Problem 1.19:
```{r}
#Chad Huntebrinker
library(Hmisc)

#Load data
y_data <- c(3.897, 3.885, 3.778, 2.54,
            3.028,
            3.865,
            2.962,
            3.961,
            0.5,
            3.178,
            3.31,
            3.538,
            3.083,
            3.013,
            3.245,
            2.963,
            3.522,
            3.013,
            2.947,
            2.118,
            2.563,
            3.357,
            3.731,
            3.925,
            3.556,
            3.101,
            2.42,
            2.579,
            3.871,
            3.06,
            3.927,
            2.375,
            2.929,
            3.375,
            2.857,
            3.072,
            3.381,
            3.29,
            3.549,
            3.646,
            2.978,
            2.654,
            2.54,
            2.25,
            2.069,
            2.617,
            2.183,
            2,
            2.952,
            3.806,
            2.871,
            3.352,
            3.305,
            2.952,
            3.547,
            3.691,
            3.16,
            2.194,
            3.323,
            3.936,
            2.922,
            2.716,
            3.37,
            3.606,
            2.642,
            2.452,
            2.655,
            3.714,
            1.806,
            3.516,
            3.039,
            2.966,
            2.482,
            2.7,
            3.92,
            2.834,
            3.222,
            3.084,
            4,
            3.511,
            3.323,
            3.072,
            2.079,
            3.875,
            3.208,
            2.92,
            3.345,
            3.956,
            3.808,
            2.506,
            3.886,
            2.183,
            3.429,
            3.024,
            3.75,
            3.833,
            3.113,
            2.875,
            2.747,
            2.311,
            1.841,
            1.583,
            2.879,
            3.591,
            2.914,
            3.716,
            2.8,
            3.621,
            3.792,
            2.867,
            3.419,
            3.6,
            2.394,
            2.286,
            1.486,
            3.885,
            3.8,
            3.914,
            1.86,
            2.94)
x_data <- c(21,
            14,
            28,
            22,
            21,
            31,
            32,
            27,
            29,
            26,
            24,
            30,
            24,
            24,
            33,
            27,
            25,
            31,
            25,
            20,
            24,
            21,
            28,
            27,
            28,
            26,
            28,
            22,
            26,
            21,
            25,
            16,
            28,
            26,
            22,
            24,
            21,
            30,
            27,
            26,
            26,
            30,
            24,
            26,
            29,
            24,
            31,
            15,
            19,
            18,
            27,
            16,
            27,
            26,
            24,
            30,
            21,
            20,
            30,
            29,
            25,
            23,
            25,
            23,
            30,
            21,
            24,
            32,
            18,
            23,
            20,
            23,
            18,
            18,
            29,
            20,
            23,
            26,
            28,
            34,
            20,
            20,
            26,
            32,
            25,
            27,
            27,
            29,
            19,
            21,
            24,
            27,
            25,
            18,
            29,
            24,
            27,
            21,
            19,
            18,
            25,
            18,
            20,
            32,
            24,
            35,
            25,
            28,
            28,
            25,
            22,
            30,
            20,
            20,
            31,
            20,
            29,
            28,
            16,
            28)
#Plot the Data
plot(y_data ~ x_data, pch = 16, xlab = "ACT Test Scores", ylab = "GPA")
minor.tick(ny = 1, tick.ratio = 0.25)

#Fit a Linear Regression model
lrgm <- lm(y_data ~ x_data)

#Find b coefficients
b_coefficients <- lrgm$coefficients

#Add the fitted line
abline(b_coefficients, lwd =2, lty =2, col="red")

```

Question 1.21
```{r}
#Load the data
x_data <- c(1, 0, 2, 0, 3, 1, 0, 1, 2, 0)
y_data <- c(16, 9, 17, 12, 22, 13, 8, 15, 19, 11)

#Plot the Data
plot(y_data ~ x_data, pch = 16, xlab = "Number of Transfers", ylab = "Number of Broken Ampules")
minor.tick(nx = 2, tick.ratio = 0.5)

#Fit a Linear Regression model
lrgm <- lm(y_data ~ x_data)

#Find b coefficients
b_coefficients <- lrgm$coefficients

#Add the fitted line
abline(b_coefficients, lwd =2, lty =2, col="red")

```

Problem 1.45
```{r}
#Chad Huntebrinker

#Length of Stay
y_data <- c(7.13,8.82,8.34,8.95,11.2,9.76,9.68,11.18,8.67,8.84,11.07,8.3,12.78,
7.58,9,11.08,8.28,11.62,9.06,9.35,7.53,10.24,9.78,9.84,9.2,8.28,
9.31,8.19,11.65,9.89,11.03,9.84,11.77,13.59,9.74,10.33,9.97,7.84,
10.47,8.16,8.48,10.72,11.2,10.12,8.37,10.16,19.56,10.9,7.67,8.88,
11.48,9.23,11.41,12.07,8.63,11.15,7.14,7.65,10.73,11.46,10.42,11.18,
7.93,9.66,7.78,9.42,10.02,8.58,9.61,8.03,7.39,7.08,9.53,10.05,8.45,
6.7,8.9,10.23,8.88,10.3,10.79,7.94,7.63,8.77,8.09,9.05,7.91,10.39,
9.36,11.41,8.86,8.93,8.92,8.15,9.77,8.54,8.66,12.01,7.95,10.15,
9.76,9.89,7.14,13.95,9.44,10.8,7.14,8.02,11.8,9.5,7.7,17.94,9.41)

#Infection Risk
x1_data <- c(4.1,1.6,2.7,5.6,5.7,5.1,4.6,
5.4,4.3,6.3,4.9,4.3,7.7,3.7,4.2,5.5,4.5,6.4,4.2,4.1,4.2,4.8,5,
4.8,4,3.9,4.5,3.2,4.4,4.9,5,5.2,5.3,6.1,6.3,5,2.8,4.6,4.1,1.3,3.7,4.7,3,
5.6,5.5,4.6,6.5,5.5,1.8,4.2,5.6,4.3,7.6,7.8,3.1,3.9,3.7,4.3,3.9,4.5,
3.4,5.7,5.4,4.4,5,4.3,4.4,3.7,4.5,3.5,4.2,2,5.2,4.5,3.4,4.5,2.9,4.9,
4.4,5.1,2.9,3.5,5.5,4.7,1.7,4.1,2.9,4.3,4.8,5.8,2.9,2,1.3,5.3,5.3,2.5,
3.8,4.8,2.3,6.2,2.6,4.3,2.7,6.6,4.5,2.9,1.4,2.1,5.7,5.8,4.4,5.9,3.1)

#Available facilities and services
x2_data <- c(60,40,20,40,40,40,40,60,40,40,80,40,57.1,37.1,17.1,57.1,37.1,37.1,
37.1,77.1,17.1,37.1,57.1,57.1,57.1,57.1,37.1,37.1,37.1,37.1,57.1,54.3,34.3,
54.3,54.3,54.3,34.3,34.3,54.3,14.3,34.3,34.3,34.3,54.3,34.3,74.3,51.4,51.4,
11.4,51.4,51.4,71.4,51.4,31.4,31.4,51.4,31.4,51.4,51.4,31.4,31.4,68.6,28.6,28.6,
48.6,48.6,48.6,48.6,48.6,28.6,28.6,28.6,48.6,68.6,48.6,28.6,28.6,68.6,48.6,45.7,
65.7,45.7,45.7,25.7,45.7,45.7,65.7,65.7,45.7,45.7,25.7,25.7,5.7,25.7,25.7,45.7,45.7,45.7,
42.9,62.9,22.9,42.9,22.9,62.9,42.9,22.9,22.9,22.9,62.9,22.9,62.9,62.9,22.9)

#Routine Chest X-ray
x3_data <- c(39.6,51.7,74,122.8,88.9,97,79,85.8,90.8,82.6,122,83.8,116.9,88,76.4,
63.6,101.8,99.2,75.9,80.9,98.9,112.6,95.9,82.3,71.1,113.1,101.3,59.2,96.1,
103.6,102.1,72.6,56,111.7,76.1,104.3,76.5,87.9,69.1,58,92.8,94.1,78.9,
79.1,84.8,51.5,113.7,71.9,40.4,86.9,82,42.6,97.9,105.3,56.2,73.9,75.8,
65.7,101,97.7,59,55.9,98.1,98.3,71.6,62.8,93,95.9,87.2,87.3,88.4,56.4,
65.7,87.5,85,80.8,86.9,77.9,76.8,88.9,56.6,92.3,61.1,47,56.9,79.8,
79.5,88.3,90.6,73,87.5,72.5,79.5,79.8,89.7,82.5,69.5,96.9,54.9,59.2,
80.1,108.7,92.6,133.5,58.5,57.4,45.7,46.5,116.9,70.9,67.9,91.8,91.7)

#For X1, plot the Data
plot(y_data ~ x1_data, pch = 16, xlab = "Infection Risk", ylab = "Length of Stay")
minor.tick(nx = 2, tick.ratio = 0.5)
#Fit a Linear Regression model
lrgm <- lm(y_data ~ x1_data)
#Find b coefficients
b_coefficients <- lrgm$coefficients
#Add the fitted line
abline(b_coefficients, lwd =2, lty =2, col="red")

#For X2, plot the Data
plot(y_data ~ x2_data, pch = 16, xlab = "Available facilities and services", ylab = "Length of Stay")
minor.tick(nx = 2, tick.ratio = 0.5)
#Fit a Linear Regression model
lrgm <- lm(y_data ~ x2_data)
#Find b coefficients
b_coefficients <- lrgm$coefficients
#Add the fitted line
abline(b_coefficients, lwd =2, lty =2, col="green")

#For X3, plot the Data
plot(y_data ~ x3_data, pch = 16, xlab = "Routine Chest X-ray", ylab = "Length of Stay")
minor.tick(nx = 2, tick.ratio = 0.5)
#Fit a Linear Regression model
lrgm <- lm(y_data ~ x3_data)
#Find b coefficients
b_coefficients <- lrgm$coefficients
#Add the fitted line
abline(b_coefficients, lwd =2, lty =2, col="blue")

```

