---
title: "Chad Huntebrinker's Homework 5"
author: "Chad Huntebrinker"
date: "2024-10-01"
output:
  word_document: default
  html_document: default
---

Question 3.3:
```{r}
#Chad Huntebrinker

library(readxl)

excel_data <- read_excel("Grade_Point_Average_Data.xlsx")

# GPA ~ ACT
# Fit the model and get the summary of the model
model_1 <- lm(GPA~ACT_Score,data=excel_data)
sum_of_model_1 <- summary(model_1)
sum_of_model_1

# Plot the graph just to see
plot(GPA~ACT_Score,data=excel_data)

#Problem 3.3a - Create boxplot
boxplot(excel_data$ACT_Score, horizontal = TRUE)

#Problem 3.3b - Create dot plot of residuals
residuals_model_1 <- resid(model_1)

stripchart(residuals_model_1, main = "Dot Plot of Residuals", xlab = "Residuals", method = "jitter")


#Problem 3.3c - Create plot of residuals against the fitted values
fitted_values <- fitted(model_1)
plot(residuals_model_1 ~ fitted_values, main = "Residual Plot", xlab = "Fitted Values", ylab = "Residuals")
abline(h = 0, lty = 2)

#Problem 3.3d - Create Normal Plot
q <- qqnorm(residuals_model_1, main = "Normal Probability Plot of Residuals")
qqline(residuals_model_1)
cor.test(q$x, q$y, method=c("pearson")) # Table B6 in book

#Problem 3.3e - calculate t sample test statistic and the Brown-Forsythe test
group_1 <- subset(excel_data, excel_data$ACT_Score < 26)
group_2 <- subset(excel_data, excel_data$ACT_Score >= 26)

model_group1 <- lm(GPA~ACT_Score,data=group_1)
model_group2 <- lm(GPA~ACT_Score,data=group_2)

median_1 <- median(resid(model_group1))
median_2 <- median(resid(model_group2))

abs_dev_group1 <- abs(resid(model_group1) - median_1)
abs_dev_group2 <- abs(resid(model_group2) - median_2)


s <- sqrt((sum((abs_dev_group1 - mean(abs_dev_group1))^2) + sum((abs_dev_group2 - mean(abs_dev_group1))^2)) 
          / (nrow(excel_data) - 2))

two_sample_t <- ((mean(abs_dev_group1) - mean(abs_dev_group2)) / (s * (sqrt(1/nrow(group_1) + 1/nrow(group_2)))))
print(two_sample_t)

#Is H0 true? We find it is not
abs(two_sample_t) > qt(0.995, 118)

#Problem 3.3f - Plot x2 and x3 with the residuals
plot(residuals_model_1 ~ excel_data$Intelligence_Test_Score, 
     main = "X2 Residual Plot", xlab = "Intelligence Test Score", ylab = "Residuals")
abline(h = 0, lty = 2)

plot(residuals_model_1 ~ excel_data$Class_Rank_Percentile, 
     main = "X3 Residual Plot", xlab = "Class Rank Percentile", ylab = "Residuals")
abline(h = 0, lty = 2)


```

Question 3.8:
```{r}
#Chad Huntebrinker

library(readxl)

excel_data <- read_excel("Crime_Rate_Data.xlsx")

# Fit the model and get the summary of the model
model_1 <- lm(Crime_Rate~Highschool_Diploma_Percentage,data=excel_data)
sum_of_model_1 <- summary(model_1)
sum_of_model_1

# Plot the graph just to see
plot(Crime_Rate~Highschool_Diploma_Percentage,data=excel_data)

#Problem 3.4a - Create stem and leaf plot
stem(excel_data$Highschool_Diploma_Percentage)

#Problem 3.4b - Create boxplot of residuals
residuals_model_1 <- resid(model_1)

boxplot(residuals_model_1, horizontal = TRUE)

#Problem 3.4c - Create a residual plot with the fitted values
fitted_values <- fitted(model_1)
plot(residuals_model_1 ~ fitted_values, main = "Residual Plot", xlab = "Fitted Values", ylab = "Residuals")
abline(h = 0, lty = 2)

#Problem 3.4d - Get the correlation coefficient and the normal probability plot
q <- qqnorm(residuals_model_1, main = "Normal Probability Plot of Residuals")
qqline(residuals_model_1)
cor.test(q$x, q$y, method=c("pearson")) # Table B6 in book

#Problem 3.4e - Do the Brown-Forsythe test
group_1 <- subset(excel_data, excel_data$Highschool_Diploma_Percentage < 69)
group_2 <- subset(excel_data, excel_data$Highschool_Diploma_Percentage >= 69)

model_group1 <- lm(Crime_Rate~Highschool_Diploma_Percentage,data=group_1)
model_group2 <- lm(Crime_Rate~Highschool_Diploma_Percentage,data=group_2)

median_1 <- median(resid(model_group1))
median_2 <- median(resid(model_group2))

abs_dev_group1 <- abs(resid(model_group1) - median_1)
abs_dev_group2 <- abs(resid(model_group2) - median_2)


s <- sqrt((sum((abs_dev_group1 - mean(abs_dev_group1))^2) + sum((abs_dev_group2 - mean(abs_dev_group1))^2)) 
          / (nrow(excel_data) - 2))

two_sample_t <- ((mean(abs_dev_group1) - mean(abs_dev_group2)) / (s * (sqrt(1/nrow(group_1) + 1/nrow(group_2)))))
print(two_sample_t)

#Is H0 true? We find it is not.
abs(two_sample_t) > qt(0.975, 82)


```

Question 3.9:
```{r}
#Chad Huntebrinker

#Problem 3.9
x_values <- c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11)
residual_values <- c(3.2, 2.9, -1.7, -2.0, -2.3, -1.2, -0.9, 0.8, 0.7, 0.5)

plot(residual_values ~ x_values)
abline(h = 0, lty = 2)

```

Question 3.11:
```{r}
#Chad Huntebrinker

#Problem 3.11a

x_values <- c(-1, 0, 1, -1, 0, 1, -1, 0, 1)
residual_values <- c(0.5, 2.1, -3.4, 0.3, -1.7, 4.2, -0.6, 2.6, -4.0)

plot(residual_values ~ x_values)
abline(h = 0, lty = 2)
#They have a megaphone type

#Problem 3.11b
m.sig <- lm(residual_values^2~x_values)
anova(m.sig)
csq <- (anova(m.sig)$"Sum Sq"[1]/2)/((anova(m.sig)$"Sum Sq"[2]/9)^2)
csq > qchisq(0.95,1)
#Ha is true

```

